[package]
name = "rtex-core"
description = "Embeddable real-time LuaTeX compilation library (core)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
rtex-dl = { path = "../rtex-dl" }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
regex.workspace = true
lopdf.workspace = true
sha2.workspace = true
hex.workspace = true
clap.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true
libc.workspace = true

[dev-dependencies]
env_logger.workspace = true
[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Pipes"] }
