[package]
name = "rtex-core"
description = "Embeddable real-time LuaTeX compilation library (core)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
rtex-dl = { path = "../rtex-dl" }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
regex.workspace = true
lopdf.workspace = true
sha2.workspace = true
hex.workspace = true
nix.workspace = true
clap.workspace = true
libc.workspace = true

[dev-dependencies]
env_logger.workspace = true
